services:

  postgres:
    image: postgres:16
    container_name: transferencias-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: transferencias_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U postgres -d transferencias_db"
        ]
      interval: 5s
      timeout: 5s
      retries: 10

    networks:
      - transferencias-network


  kafka:
    image: apache/kafka:4.3.1
    platform: linux/amd64
    container_name: transferencias-kafka
    restart: unless-stopped

    ports:
      - "29092:29092"

    environment:
      KAFKA_NODE_ID: 1

      KAFKA_PROCESS_ROLES: broker,controller

      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,PLAINTEXT_HOST://:29092

      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT

      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "/opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --list"
        ]
      interval: 10s
      timeout: 10s
      retries: 10

    networks:
      - transferencias-network

  backend:
    container_name: transferencias-backend

    build:
      context: ./Backend
      dockerfile: Dockerfile

    restart: unless-stopped

    ports:
      - "8080:8080"

    environment:

      ASPNETCORE_ENVIRONMENT: Development

      ASPNETCORE_URLS: http://+:8080

      ConnectionStrings__DefaultConnection: >
        Host=postgres;
        Port=5432;
        Database=transferencias_db;
        Username=postgres;
        Password=postgres

      Kafka__BootstrapServers: kafka:9092

      TransferRules__TimeZone: America/Sao_Paulo
      TransferRules__DayStartHour: 6
      TransferRules__NightStartHour: 22

    depends_on:

      postgres:
        condition: service_healthy

      kafka:
        condition: service_healthy

    networks:
      - transferencias-network


volumes:

  postgres_data:


networks:

  transferencias-network:
    driver: bridge